# Generated by Django 5.1.1 on 2024-10-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderproduct_variation_orderproduct_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
