# Generated by Django 5.1.1 on 2024-10-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderproduct_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='is_ordered',
        ),
    ]
