# Generated by Django 5.1.1 on 2024-10-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderproduct_is_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variation',
            new_name='variations',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='is_ordered',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
